### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jlafleche**

### CODE REVIEW

**Comment by jlafleche** [comment]
can

**Comment by jlafleche** [comment]
you

**Comment by jlafleche** [comment]
write

**Comment by jlafleche** [comment]
comments.

**Comment by jlafleche** [comment]
I should have

**Comment by jlafleche** [comment]
automated this.

**Comment by jlafleche** [comment]
**LGTM**

**Comment by jlafleche** [comment]
```
LGTM
```

**Comment by jlafleche** [comment]
yeah sure w/e

**Comment by jlafleche** [comment]
@brianbao

**Comment by jlafleche** [comment]
kew kew :smile:

**Comment by jlafleche** [comment]
kew kew kew :smile_cat:

**Comment by jlafleche** [comment]
1234567

**Comment by jlafleche** [comment]
3243241

**Comment by jlafleche** [comment]
3124324123432442311234

**Comment by jlafleche** [comment]
324

**Comment by jlafleche** [comment]
3241324

**Comment by jlafleche** [comment]
32413241

**Comment by jlafleche** [comment]
324

**Comment by jlafleche** [comment]
Why

**Comment by jlafleche** [comment]
Do

**Comment by jlafleche** [comment]
Birds

**Comment by jlafleche** [comment]
Suddenly

**Comment by jlafleche** [comment]
Suddenly

**Comment by jlafleche** [comment]
Suddenly

**Comment by jlafleche** [comment]
Suddenly

**Comment by jlafleche** [comment]
curl is cool

**Comment by jlafleche** [comment]
curlIsCcool

**Comment by jlafleche** [comment]
curlIsCool

**Comment by jlafleche** [comment]
curlIsCool

**Comment by jlafleche** [comment]
curlIsCool

**Comment by jlafleche** [comment]
curlIsCool

**Comment by jlafleche** [comment]
curlIsCool

**Comment by jlafleche** [comment]
curlIsCool

**Comment by jlafleche** [comment]
curlIsCool

**Comment by jlafleche** [comment]
curlIsCool

**Comment by jlafleche** [comment]
curlIsCool

**Comment by brianbao** [comment]
stop

**Comment by brianbao** [comment]
you are embarrassing me

**Pull request closed without merging**
